# Generated by Django 3.2 on 2021-05-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field_name', models.CharField(help_text='Film naming', max_length=100)),
                ('ajax_href', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('kp_rating', models.FloatField(max_length=100)),
                ('imdb_rating', models.FloatField()),
                ('singleGenre', models.CharField(max_length=30)),
            ],
        ),
    ]
