# Generated by Django 3.2 on 2021-05-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='my_field_name',
            new_name='name',
        ),
    ]
