# Generated by Django 3.2 on 2021-05-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_film_ajax_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='ajax_href',
        ),
        migrations.RemoveField(
            model_name='film',
            name='imdb_rating',
        ),
        migrations.RemoveField(
            model_name='film',
            name='kp_rating',
        ),
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
