# Generated by Django 3.2 on 2021-05-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_auto_20210507_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ('-rating',)},
        ),
    ]
