# Generated by Django 3.1.1 on 2021-05-17 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_auto_20210517_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='film',
        ),
    ]
