# Generated by Django 3.1.1 on 2021-06-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_auto_20210528_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(help_text='Film naming', max_length=100, unique=True),
        ),
    ]
