# Generated by Django 3.1.1 on 2021-06-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0014_auto_20210622_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
