# Generated by Django 3.1.1 on 2021-06-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0016_comment_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reason_for_deleting',
            field=models.TextField(blank=True),
        ),
    ]
