# Generated by Django 3.1.1 on 2021-06-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='d',
            field=models.TextField(blank=True, max_length=2),
        ),
    ]
