# Generated by Django 3.1.1 on 2021-06-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
