# Generated by Django 3.1.1 on 2021-06-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210627_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='d',
        ),
    ]
