# Generated by Django 3.1.1 on 2021-06-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
