# Generated by Django 3.1.1 on 2021-06-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210621_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videofile', models.FileField(upload_to='blog/temp_videos/')),
            ],
        ),
    ]
