# Generated by Django 3.1.1 on 2021-06-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_tempvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempvideo',
            name='video_name',
            field=models.CharField(default=555, max_length=200),
            preserve_default=False,
        ),
    ]
