# Generated by Django 3.1.1 on 2021-06-21 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_tempvideo_video_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempvideo',
            name='video_name',
        ),
    ]
